org: devkindr
app: kinder
service: node-lambda-dynamodb-setup

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-split-stacks

useDotenv: true

package:
  exclude:
    - node_modules/**

custom:
  stage: dev
  dynamoDBTable:
    Users: ${self:custom.stage}-Users
    organizations: ${self:custom.stage}-organizations
    OrganizationSettings: ${self:custom.stage}-OrganizationSetting
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: true
    nestedStackCount: 2

provider:
  name: aws
  deploymentMethod: changesets
  runtime: nodejs16.x
  region: us-east-2
  memorySize: 256
  stage: ${self:custom.stage}
  timeout: 30
  architecture: arm64
  versionFunctions: false
  environment:
    DYNAMODB_TABLE_USERS: ${self:custom.dynamoDBTable.Users}
    DYNAMODB_TABLE_ORGANIZATIONS: ${self:custom.dynamoDBTable.organizations}
    DYNAMODB_TABLE_ORGANIZATIONS_SETTINGS: ${self:custom.dynamoDBTable.OrganizationSettings}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamoDBTable.Users}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamoDBTable.organizations}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamoDBTable.OrganizationSettings}
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoDBTable.Users}
        AttributeDefinitions:
          - AttributeName: org_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: org_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        BillingMode: PROVISIONED
        Tags:
          - Key: Name
            Value: ${self:custom.dynamoDBTable.Users}

    OrganizationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoDBTable.organizations}
        AttributeDefinitions:
          - AttributeName: org_id
            AttributeType: S
          - AttributeName: org_name
            AttributeType: S
        KeySchema:
          - AttributeName: org_id
            KeyType: HASH
          - AttributeName: org_name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        BillingMode: PROVISIONED
        Tags:
          - Key: Name
            Value: ${self:custom.dynamoDBTable.organizations}

    OrganizationSettingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoDBTable.OrganizationSettings}
        AttributeDefinitions:
          - AttributeName: org_id
            AttributeType: S
          - AttributeName: settings
            AttributeType: S
        KeySchema:
          - AttributeName: org_id
            KeyType: HASH
          - AttributeName: settings
            KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        BillingMode: PROVISIONED
        Tags:
          - Key: Name
            Value: ${self:custom.dynamoDBTable.OrganizationSettings}

functions:
  register:
    handler: services/user/handler.registerUser
    memorySize: 256
    events:
      - http:
          path: /api/v1/user/register
          method: post
          cors:
            origin: "*"
            headers: "*"
  onboardCreate:
    handler: services/user/handler.onboardCreate
    memorySize: 256
    events:
      - http:
          path: /api/v1/user/onboardCreate
          method: post
          cors:
            origin: "*"
            headers: "*"
  getOrganizationSettingsByName:
    handler: services/settings/handler.getOrganizationSettingsByName
    memorySize: 256
    events:
      - http:
          path: /api/v1/getOrganizationSettingsByName/{org_name}
          method: get
          cors:
            origin: "*"
            headers: "*"
  getOrganizationSettingsById:
    handler: services/settings/handler.getOrganizationSettingsById
    memorySize: 256
    events:
      - http:
          path: /api/v1/getOrganizationSettingsById/{org_id}
          method: get
          cors:
            origin: "*"
            headers: "*"
