AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: The deployment stage

Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        DYNAMODB_TABLE_USERS: !Sub "${Stage}-Users"
        DYNAMODB_TABLE_ORGANIZATIONS: !Sub "${Stage}-organizations"
        DYNAMODB_TABLE_ORGANIZATIONS_SETTINGS: !Sub "${Stage}-OrganizationSetting"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Stage}-api"
      StageName: !Ref Stage
      DefinitionBody:
        swagger: '2.0'
        info:
          title: My API
          version: '1.0'
        paths:
          /api/v1/user/register:
            post:
              produces:
                - application/json
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUserFunction.Arn}/invocations
          /api/v1/user/onboardCreate:
            post:
              produces:
                - application/json
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnboardCreateFunction.Arn}/invocations
          /api/v1/getOrganizationSettingsByName/{org_name}:
            get:
              produces:
                - application/json
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: GET
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetOrganizationSettingsByNameFunction.Arn}/invocations
          /api/v1/getOrganizationSettingsById/{org_id}:
            get:
              produces:
                - application/json
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: GET
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetOrganizationSettingsByIdFunction.Arn}/invocations
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}-Users"
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: Name
          Value: !Sub "${Stage}-Users"

  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}-organizations"
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: org_name
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: org_name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: Name
          Value: !Sub "${Stage}-organizations"

  OrganizationSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}-OrganizationSetting"
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: settings
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: settings
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: Name
          Value: !Sub "${Stage}-OrganizationSetting"

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/user/handler.registerUser
      Events:
        RegisterUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/user/register
            Method: post

  OnboardCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/user/handler.onboardCreate
      Events:
        OnboardCreateApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/user/onboardCreate
            Method: post

  GetOrganizationSettingsByNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/settings/handler.getOrganizationSettingsByName
      Events:
        GetOrgSettingsByNameApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/getOrganizationSettingsByName/{org_name}
            Method: get

  GetOrganizationSettingsByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/settings/handler.getOrganizationSettingsById
      Events:
        GetOrgSettingsByIdApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/getOrganizationSettingsById/{org_id}
            Method: get

Outputs:
  UsersTableName:
    Value: !Sub "${Stage}-Users"
  OrganizationsTableName:
    Value: !Sub "${Stage}-organizations"
  OrganizationSettingsTableName:
    Value: !Sub "${Stage}-OrganizationSetting"
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
